#pragma once

#include <juce_dsp/juce_dsp.h>

#include "../Models/Fairchild/Fairchild670Core.h"

namespace DSP {

// ─────────────────────────────────────────────────────────────────────────────

/// Oversampling wrapper around the Fairchild 670 stereo core.
///
/// Wraps `juce::dsp::Oversampling` around a `Models::Fairchild670Core` to
/// reduce aliasing generated by the nonlinear (variable-mu triode) stages:
///
///   Audio in → upsample → Fairchild670Core → downsample → Audio out
///
/// The core is prepared at the oversampled sample rate, so all internal time
/// constants (detector attack/release, cathode capacitors) remain correct.
///
/// Usage:
///   1. Call setOversamplingOrder() / setQuality() to configure (optional;
///      defaults to 1× / High).
///   2. Call prepare() in prepareToPlay().
///   3. Call process() each audio block.
///   4. Pass getLatencySamples() to the host via setLatencySamples().
///
/// Thread safety:
///   - prepare() and process() must not be called concurrently.
///   - setOversamplingOrder() triggers a safe reinit on the next prepare()
///     (or immediately if already prepared, but NOT from the audio thread).
///   - setQuality() is safe to call from the audio thread between blocks.
class OversamplingChain {
public:
    OversamplingChain();
    ~OversamplingChain() = default;

    // ── Lifecycle ────────────────────────────────────────────────────────────

    /// Prepare for the given sample rate and maximum block size.
    ///
    /// Must be called at least once before process().  Safe to call multiple
    /// times (e.g. in response to an oversampling order change); rebuilds the
    /// oversampling filter and re-prepares the core at the oversampled rate.
    void prepare(double sampleRate, int maxBlockSize);

    /// Reset all filter and model state to initial conditions.
    void reset();

    // ── Processing ───────────────────────────────────────────────────────────

    /// Process a stereo buffer in-place through the oversampler and core.
    ///
    /// The buffer must have exactly 2 channels.  Passing a mono or
    /// multi-channel buffer is undefined behaviour.
    void process(juce::AudioBuffer<float>& buffer);

    // ── Latency ──────────────────────────────────────────────────────────────

    /// Oversampling filter latency in samples at the host (non-oversampled)
    /// sample rate.  Pass to AudioProcessor::setLatencySamples().
    ///
    /// Returns 0 when oversampling is set to 1× (no filter).
    [[nodiscard]] int getLatencySamples() const noexcept;

    // ── Configuration ────────────────────────────────────────────────────────

    /// Set the oversampling factor as a base-2 exponent (0 = 1×, 1 = 2×,
    /// 2 = 4×, 3 = 8×).
    ///
    /// Triggers an internal rebuild of the oversampling filter.  If prepare()
    /// has already been called, the oversampler is reinitialised immediately;
    /// this involves memory allocation and must therefore be called from the
    /// message thread (e.g. in prepareToPlay or in response to a parameter
    /// change detected outside the audio callback).
    void setOversamplingOrder(int order);

    /// Adjust the NR iteration budget on both variable-mu gain stages.
    ///
    /// Delegates to Models::Fairchild670Core::setQuality().  Safe to call
    /// between audio blocks (no prepare needed).
    void setQuality(Models::ProcessingQuality quality);

    // ── Core access ──────────────────────────────────────────────────────────

    /// Direct access to the Fairchild 670 core for link mode, timing position,
    /// meter readback, and other configuration that is not oversampling-related.
    [[nodiscard]] Models::Fairchild670Core& core() noexcept { return core_; }
    [[nodiscard]] const Models::Fairchild670Core& core() const noexcept { return core_; }

private:
    /// Rebuild the juce::dsp::Oversampling object and call initProcessing().
    /// Called from prepare() and from setOversamplingOrder() when already prepared.
    void rebuildOversampler();

    Models::Fairchild670Core core_;

    /// Null when order_ == 0 (1× — no oversampling object needed).
    std::unique_ptr<juce::dsp::Oversampling<float>> oversampler_;

    double sampleRate_   = 44100.0;
    int    maxBlockSize_ = 512;

    /// Current oversampling order (base-2 exponent: 0 = 1×, 1 = 2×, …).
    int order_ = 0;

    bool prepared_ = false;
};

} // namespace DSP
