#!/usr/bin/env python3
"""
plot_timing.py — Plot attack/release step-response CSV produced by the
phu_calibrate tool.

Usage:
    python3 scripts/plot_timing.py <timing_csv> [--output <image.png>]

The CSV is generated by:
    ./build/tools/phu_calibrate --measure-timing --position <1-6>

Example:
    ./build/tools/phu_calibrate --measure-timing --position 1 > /tmp/p1_timing.csv
    python3 scripts/plot_timing.py /tmp/p1_timing.csv --output /tmp/p1_timing.png
"""

import argparse
import csv
import sys
from pathlib import Path


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Plot Fairchild 670 timing step-response CSV.")
    p.add_argument("csv_file", help="CSV file produced by phu_calibrate --measure-timing")
    p.add_argument("--output", "-o", default=None,
                   help="Output image path (PNG). If omitted, displays interactively.")
    return p.parse_args()


def load_csv(path: str) -> tuple[list, dict]:
    """Load CSV, skipping comment lines. Return (rows, metadata_dict)."""
    meta: dict = {}
    rows: list = []

    with open(path, newline="") as f:
        for line in f:
            line = line.rstrip()
            if line.startswith("#"):
                # Parse key=value pairs from comment header.
                for token in line.lstrip("# ").split():
                    if "=" in token:
                        k, v = token.split("=", 1)
                        meta[k] = v
                continue
            if not rows and "sample_index" in line:
                # Header row
                header = [c.strip() for c in line.split(",")]
                continue
            parts = [p.strip() for p in line.split(",")]
            if len(parts) >= 5:
                rows.append({
                    "sample_index": int(parts[0]),
                    "phase":        parts[1],
                    "input":        float(parts[2]),
                    "cv_volts":     float(parts[3]),
                    "time_sec":     float(parts[4]),
                })
    return rows, meta


def main() -> None:
    args = parse_args()

    try:
        import matplotlib.pyplot as plt
    except ImportError:
        print("matplotlib is required: pip install matplotlib", file=sys.stderr)
        sys.exit(1)

    rows, meta = load_csv(args.csv_file)
    if not rows:
        print("No data found in CSV.", file=sys.stderr)
        sys.exit(1)

    attack_rows  = [r for r in rows if r["phase"] == "attack"]
    release_rows = [r for r in rows if r["phase"] == "release"]

    pos     = meta.get("position", "?")
    kind    = meta.get("kind", "?")
    atk_s   = meta.get("attack_sec", "?")
    rel_s   = meta.get("release_sec", "?")

    fig, axes = plt.subplots(1, 2, figsize=(12, 5))
    title_base = f"Fairchild 670 Timing — Position {pos} ({kind})"

    # Attack plot.
    ax = axes[0]
    if attack_rows:
        t = [r["time_sec"] * 1000.0 for r in attack_rows]  # ms
        cv = [r["cv_volts"] for r in attack_rows]
        ax.plot(t, cv, color="#e07b39", linewidth=1.5, label="CV (V)")
        # 63.2 % reference line.
        final_v = max(cv) if cv else 10.0
        ax.axhline(final_v * 0.632, color="gray", linestyle="--", linewidth=0.8, label="63.2 %")
    ax.set_title(f"Attack  (τ ≈ {atk_s} s)")
    ax.set_xlabel("Time (ms)")
    ax.set_ylabel("Control voltage (V)")
    ax.legend()
    ax.grid(True, alpha=0.3)

    # Release plot.
    ax = axes[1]
    if release_rows:
        # Re-zero time to start of release phase.
        t0 = release_rows[0]["time_sec"]
        t  = [(r["time_sec"] - t0) for r in release_rows]
        cv = [r["cv_volts"] for r in release_rows]
        ax.plot(t, cv, color="#5b8dd9", linewidth=1.5, label="CV (V)")
        # 36.8 % reference line.
        initial_v = cv[0] if cv else 10.0
        ax.axhline(initial_v * 0.368, color="gray", linestyle="--", linewidth=0.8, label="36.8 %")
    ax.set_title(f"Release  (τ ≈ {rel_s} s)")
    ax.set_xlabel("Time (s)")
    ax.set_ylabel("Control voltage (V)")
    ax.legend()
    ax.grid(True, alpha=0.3)

    fig.suptitle(title_base, fontsize=13)
    plt.tight_layout()

    if args.output:
        plt.savefig(args.output, dpi=150)
        print(f"Saved: {args.output}")
    else:
        plt.show()


if __name__ == "__main__":
    main()
