#!/usr/bin/env python3
"""
plot_transfer.py — Plot input-vs-output transfer-curve CSV produced by the
phu_calibrate tool.

Usage:
    python3 scripts/plot_transfer.py <transfer_csv> [--reference <ref_csv>]
                                     [--output <image.png>]

The CSV is generated by:
    ./build/tools/phu_calibrate --measure-transfer --position <1-6>

A manual-derived reference CSV (e.g. tests/transfer_curve_reference.csv) can be
overlaid for visual comparison.

Example:
    ./build/tools/phu_calibrate --measure-transfer --position 1 > /tmp/p1_transfer.csv
    python3 scripts/plot_transfer.py /tmp/p1_transfer.csv \\
        --reference tests/transfer_curve_reference.csv \\
        --output /tmp/p1_transfer.png
"""

import argparse
import sys


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Plot Fairchild 670 transfer-curve CSV.")
    p.add_argument("csv_file", help="CSV from phu_calibrate --measure-transfer")
    p.add_argument("--reference", "-r", default=None,
                   help="Optional manual-derived reference CSV for overlay.")
    p.add_argument("--output", "-o", default=None,
                   help="Output image path (PNG). If omitted, displays interactively.")
    return p.parse_args()


def load_transfer_csv(path: str) -> tuple[list, dict]:
    meta: dict = {}
    rows: list = []
    with open(path, newline="") as f:
        header_seen = False
        for line in f:
            line = line.rstrip()
            if line.startswith("#"):
                for token in line.lstrip("# ").split():
                    if "=" in token:
                        k, v = token.split("=", 1)
                        meta[k] = v
                continue
            if not header_seen and "input_dbfs" in line:
                header_seen = True
                continue
            parts = [p.strip() for p in line.split(",")]
            if len(parts) >= 3:
                try:
                    rows.append({
                        "input_dbfs":  float(parts[0]),
                        "output_dbfs": float(parts[1]),
                        "gr_db":       float(parts[2]),
                    })
                except ValueError:
                    pass
    return rows, meta


def main() -> None:
    args = parse_args()

    try:
        import matplotlib.pyplot as plt
    except ImportError:
        print("matplotlib is required: pip install matplotlib", file=sys.stderr)
        sys.exit(1)

    rows, meta = load_transfer_csv(args.csv_file)
    if not rows:
        print("No data found in CSV.", file=sys.stderr)
        sys.exit(1)

    pos  = meta.get("position", "?")
    kind = meta.get("kind", "?")

    fig, axes = plt.subplots(1, 2, figsize=(13, 5))

    # --- Left panel: input vs output ---
    ax = axes[0]
    in_vals  = [r["input_dbfs"]  for r in rows]
    out_vals = [r["output_dbfs"] for r in rows]

    ax.plot(in_vals, out_vals, marker="o", color="#e07b39", linewidth=1.5,
            label="Measured", markersize=4)

    # Unity-gain reference line.
    min_v = min(in_vals + out_vals) - 2
    ax.plot([min_v, 0], [min_v, 0], "--", color="gray", linewidth=0.8, label="Unity gain")

    if args.reference:
        ref_rows, _ = load_transfer_csv(args.reference)
        ref_in  = [r["input_dbfs"]  for r in ref_rows]
        ref_out = [r["output_dbfs"] for r in ref_rows]
        ax.plot(ref_in, ref_out, marker="s", color="#5b8dd9", linewidth=1.2,
                linestyle="--", label="Manual reference", markersize=4)

    ax.set_title(f"Transfer Curve — Position {pos} ({kind})")
    ax.set_xlabel("Input (dBFS)")
    ax.set_ylabel("Output (dBFS)")
    ax.legend()
    ax.grid(True, alpha=0.3)

    # --- Right panel: gain reduction vs input ---
    ax = axes[1]
    gr_vals = [r["gr_db"] for r in rows]
    ax.plot(in_vals, gr_vals, marker="o", color="#e07b39", linewidth=1.5,
            label="Measured GR", markersize=4)
    ax.axhline(0, color="gray", linestyle="--", linewidth=0.8)

    if args.reference:
        ref_rows, _ = load_transfer_csv(args.reference)
        ref_in = [r["input_dbfs"] for r in ref_rows]
        ref_gr = [r["gr_db"]      for r in ref_rows]
        ax.plot(ref_in, ref_gr, marker="s", color="#5b8dd9", linewidth=1.2,
                linestyle="--", label="Manual reference GR", markersize=4)

    ax.set_title("Gain Reduction")
    ax.set_xlabel("Input (dBFS)")
    ax.set_ylabel("Gain reduction (dB)")
    ax.legend()
    ax.grid(True, alpha=0.3)

    fig.suptitle(f"Fairchild 670 Transfer — Position {pos}", fontsize=13)
    plt.tight_layout()

    if args.output:
        plt.savefig(args.output, dpi=150)
        print(f"Saved: {args.output}")
    else:
        plt.show()


if __name__ == "__main__":
    main()
